public enum CoachOutputSchemaVersion: String, Sendable, Codable, Equatable, CaseIterable {
    case chatV1 = "chat.v1"
    case sessionAdjustmentV1 = "session_adjustment.v1"
    case sessionAdjustmentV2 = "session_adjustment.v2"
    case mealEstimateV1 = "meal_estimate.v1"
    case mealDecompositionV1 = "meal_decomposition.v1"
    case settingsAdjustmentV1 = "settings_adjustment.v1"
    case memoryAdjustmentV1 = "memory_adjustment.v1"
    case workoutStartV1 = "workout_start.v1"
    case workoutStartV2 = "workout_start.v2"
    case foodLogV1 = "food_log.v1"
    case mealQueryV1 = "meal_query.v1"
    case mealCopyV1 = "meal_copy.v1"
    case workoutQueryV1 = "workout_query.v1"
    case recoveryQueryV1 = "recovery_query.v1"
    case chartV1 = "chart.v1"
    case briefV1 = "brief.v1"
}
